CREATE TABLE Art (
    [ArtID] INT PRIMARY KEY IDENTITY,
    [Title] NVARCHAR(100) NOT NULL,
    [Artist] NVARCHAR(100) NOT NULL,
    [Year] INT NOT NULL,
    [Price] DECIMAL(10, 2) NOT NULL,
    [Artwork] NVARCHAR(255) NOT NULL,
    [CreatedAt] DATETIME NOT NULL DEFAULT SYSUTCDATETIME(), 
    [ProfileID] INT NOT NULL,
    CONSTRAINT FK_Art_ProfileID FOREIGN KEY (ProfileID) REFERENCES [dbo].[Profile](ProfileID)
);